Fix issue reported on the forums:
Caused by:

java.util.regex.PatternSyntaxException: Dangling meta character '+' near index 48
/private/var/folders/0a/0ajcnh+hGzuwRCjcXfj0QU+++TI/-Tmp-/Jetty_0_0_0_0_8080_ajax.request.war____22hbzl/webapp/
                                                ^
	at java.util.regex.Pattern.error(Pattern.java:1713)
	at java.util.regex.Pattern.sequence(Pattern.java:1878)
	at java.util.regex.Pattern.expr(Pattern.java:1752)
	at java.util.regex.Pattern.compile(Pattern.java:1460)
	at java.util.regex.Pattern.(Pattern.java:1133)
	at java.util.regex.Pattern.compile(Pattern.java:823)
	at java.lang.String.replaceFirst(String.java:2146)
	at com.sun.faces.facelets.impl.DefaultFaceletFactory.createMetadataFacelet(DefaultFaceletFactory.java:335)